import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a>!
        </h1>
        <br />
        <br />
        <br />

        <button
          type="button"
          className={styles.button__error}
          onClick={() => {
            throw new Error("Sentry Frontend Error from custom Tunnel");
          }}
        >
          Throw error with tunnel
        </button>
      </main>

      <footer className={styles.footer}>
        <div className="box">
          Powered by{" "}
          <a
            href="https://vercel.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            <span className={styles.logo}>
              <Image
                src="/vercel_logo.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
          <span style={{ paddingLeft: 6 }}>&</span>
          <a href="https://sentry.io" target="_blank" rel="noopener noreferrer">
            <span className={styles.logo}>
              <Image
                src="/sentry_logo.svg"
                alt="Sentry Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </div>
      </footer>
    </div>
  );
}
