{"sent_at":"2022-07-11T07:25:36.862Z","sdk":{"name":"sentry.javascript.react","version":"7.5.1"},"dsn":"https://d5dca0bc5fa14f0898c21831520fdfae@sentry.example.com/4"}
{"type":"session"}
{"sid":"13739afaa5214be18b99df897bc4dc9d","init":true,"started":"2022-07-11T07:25:36.861Z","timestamp":"2022-07-11T07:25:36.861Z","status":"ok","errors":0,"attrs":{"release":"accounts@local","environment":"local","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}}