source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'

node_modules_path = './node_modules' # This path can be different depending on you setup
react_path = File.join(node_modules_path, 'react-native')
yoga_path = File.join(react_path, 'ReactCommon/yoga')
sentry_path = File.join(node_modules_path, 'react-native-sentry')

target 'ios-swift-cocoapods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'DoubleConversion', :podspec => react_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => react_path + '/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => react_path + '/third-party-podspecs/Folly.podspec'

  pod 'React', :path => react_path, :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'Yoga', :path => yoga_path

  pod 'SentryReactNative', :path => sentry_path

  target 'ios-swift-cocoapodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
